from pathlib import Path
text = Path('src/i18n/translations.ts').read_text(encoding='utf-8')

german_block = "    settings: {\n      title: 'Einstellungen',\n      subtitle: 'Passe dein Profil an',\n      profile: 'Profil',\n      editProfile: 'Profil bearbeiten',\n      saveChanges: 'Änderungen speichern',\n      nickname: 'Spitzname',\n      gender: 'Geschlecht',\n      male: 'Männlich',\n      female: 'Weiblich',\n      diverse: 'Divers',\n      height: 'Größe (cm)',\n      weight: 'Gewicht (kg)',\n      bodyFat: 'KFA (%) - Optional',\n      maxPushups: 'Max. Liegestütze',\n      birthday: 'Geburtstag',\n      language: 'Sprache',\n      darkMode: 'Dark Mode',\n      darkModeDesc: 'Dunkles Farbschema verwenden',\n      appearance: 'Darstellung',\n      group: 'Gruppe',\n      currentGroup: 'Aktuelle Gruppe',\n      noGroup: 'Keine Gruppe',\n      yourGroupCode: 'Dein Gruppencode',\n      joinGroup: 'Beitreten',\n      joinOrCreateGroup: 'Gruppe beitreten oder erstellen',\n      leaveGroup: 'Gruppe verlassen',\n      groupCodePlaceholder: 'GRUPPENCODE',\n      enterCode: 'Gruppencode eingeben',\n      join: 'Beitreten',\n      notifications: 'Benachrichtigungen',\n      dailyReminder: 'Tägliche Erinnerung',\n      changeTime: 'Zeit ändern',\n      testNotification: 'Test-Benachrichtigung senden',\n      reminderTime: 'Erinnerungszeit',\n      account: 'Konto',\n      logout: 'Abmelden',\n      deleteAccount: 'Konto löschen',\n      legal: 'Rechtliches',\n      privacy: 'Datenschutzerklärung',\n      terms: 'Nutzungsbedingungen',\n      profileUpdated: 'Profil aktualisiert!',\n      saveError: 'Fehler beim Speichern',\n      joinedGroup: 'Erfolgreich der Gruppe beigetreten!',\n      joinGroupError: 'Fehler beim Beitreten der Gruppe',\n    },"

new_german_block = "    settings: {\n      title: 'Einstellungen',\n      subtitle: 'Passe dein Profil an',\n      profile: 'Profil',\n      editProfile: 'Profil bearbeiten',\n      saveChanges: 'Änderungen speichern',\n      nickname: 'Spitzname',\n      gender: 'Geschlecht',\n      male: 'Männlich',\n      female: 'Weiblich',\n      diverse: 'Divers',\n      height: 'Größe (cm)',\n      weight: 'Gewicht (kg)',\n      bodyFat: 'KFA (%) - Optional',\n      maxPushups: 'Max. Liegestütze',\n      birthday: 'Geburtstag',\n      language: 'Sprache',\n      darkMode: 'Dark Mode',\n      darkModeDesc: 'Dunkles Farbschema verwenden',\n      appearance: 'Darstellung',\n      installSection: 'App-Installation',\n      installDescription: 'Installiere die App, damit sie wie eine native Anwendung funktioniert und offline verfügbar ist.',\n      installButton: 'Installationsdialog öffnen',\n      installHelp: 'Installationshinweise anzeigen',\n      showInstructions: 'Anleitung anzeigen',\n      hideInstructions: 'Anleitung verbergen',\n      installInstructions: 'Falls kein Dialog erscheint: Öffne die Browser-Menüleiste und wähle "Zum Startbildschirm hinzufügen".',\n      installInstructionsIos: 'Öffne die Seite in Safari, tippe auf das Teilen-Symbol und wähle "Zum Home-Bildschirm".',\n      installAlready: 'Die App ist bereits installiert. Du kannst sie direkt vom Home-Bildschirm starten.',\n      group: 'Gruppe',\n      currentGroup: 'Aktuelle Gruppe',\n      noGroup: 'Keine Gruppe',\n      yourGroupCode: 'Dein Gruppencode',\n      joinGroup: 'Beitreten',\n      joinOrCreateGroup: 'Gruppe beitreten oder erstellen',\n      leaveGroup: 'Gruppe verlassen',\n      groupCodePlaceholder: 'GRUPPENCODE',\n      enterCode: 'Gruppencode eingeben',\n      join: 'Beitreten',\n      notifications: 'Benachrichtigungen',\n      dailyReminder: 'Tägliche Erinnerung',\n      reminderTime: 'Erinnerungszeit',\n      hydrationReminder: 'Hydration (morgens)',\n      proteinReminder: 'Protein (mittags)',\n      pushupReminder: 'Liegestütze (abends)',\n      changeTime: 'Zeit ändern',\n      testNotification: 'Test-Benachrichtigung senden',\n      account: 'Konto',\n      logout: 'Abmelden',\n      deleteAccount: 'Konto löschen',\n      legal: 'Rechtliches',\n      privacy: 'Datenschutzerklärung',\n      terms: 'Nutzungsbedingungen',\n      profileUpdated: 'Profil aktualisiert!',\n      saveError: 'Fehler beim Speichern',\n      joinedGroup: 'Erfolgreich der Gruppe beigetreten!',\n      joinGroupError: 'Fehler beim Beitreten der Gruppe',\n    },"

if german_block in text:
    text = text.replace(german_block, new_german_block)

Path('src/i18n/translations.ts').write_text(text, encoding='utf-8')
