from pathlib import Path
text = Path('src/i18n/translations.ts').read_text(encoding='utf-8')

if "installSection" not in text:
    german_old = "      notifications: 'Benachrichtigungen',\n      reminderTime: 'Erinnerungszeit',\n      changeTime: 'Zeit ändern',\n      testNotification: 'Testbenachrichtigung',\n      profileUpdated: 'Profil aktualisiert!',\n"
    german_new = "      notifications: 'Benachrichtigungen',\n      reminderTime: 'Erinnerungszeit',\n      changeTime: 'Zeit ändern',\n      testNotification: 'Testbenachrichtigung',\n      installSection: 'App-Installation',\n      installDescription: 'Installiere die App, damit sie wie eine native Anwendung funktioniert und offline verfügbar ist.',\n      installButton: 'Installationsdialog öffnen',\n      installHelp: 'Installationshinweise anzeigen',\n      showInstructions: 'Anleitung anzeigen',\n      hideInstructions: 'Anleitung verbergen',\n      installInstructions: 'Falls kein Dialog erscheint: Öffne die Browser-Menüleiste und wähle „Zum Startbildschirm hinzufügen“.',\n      installInstructionsIos: 'Öffne die Seite in Safari, tippe auf das Teilen-Symbol und wähle „Zum Home-Bildschirm“.',\n      installAlready: 'Die App ist bereits installiert. Du kannst sie direkt vom Home-Bildschirm starten.',\n      profileUpdated: 'Profil aktualisiert!',\n"
    english_old = "      notifications: 'Notifications',\n      reminderTime: 'Reminder Time',\n      changeTime: 'Change Time',\n      testNotification: 'Test Notification',\n      profileUpdated: 'Profile updated!',\n"
    english_new = "      notifications: 'Notifications',\n      reminderTime: 'Reminder Time',\n      changeTime: 'Change Time',\n      testNotification: 'Test Notification',\n      installSection: 'Install App',\n      installDescription: 'Install the app for a native-like experience and offline access.',\n      installButton: 'Open install dialog',\n      installHelp: 'Show installation tips',\n      showInstructions: 'Show instructions',\n      hideInstructions: 'Hide instructions',\n      installInstructions: 'If no prompt appears, open the browser menu and choose “Add to homescreen”.',\n      installInstructionsIos: 'Open this site in Safari, tap the share icon, then choose “Add to Home Screen”.',\n      installAlready: 'The app is already installed. Launch it directly from your homescreen.',\n      profileUpdated: 'Profile updated!',\n"
    text = text.replace(german_old, german_new, 1)
    text = text.replace(english_old, english_new, 1)

Path('src/i18n/translations.ts').write_text(text, encoding='utf-8')
