from pathlib import Path

TRANSLATIONS_PATH = Path("src/i18n/translations.ts")
text = TRANSLATIONS_PATH.read_text(encoding="utf-8")

german_block = """    settings: {
      title: 'Einstellungen',
      subtitle: 'Passe dein Profil an',
      profile: 'Profil',
      editProfile: 'Profil bearbeiten',
      saveChanges: 'Änderungen speichern',
      nickname: 'Spitzname',
      gender: 'Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      diverse: 'Divers',
      height: 'Größe (cm)',
      weight: 'Gewicht (kg)',
      bodyFat: 'KFA (%) - Optional',
      maxPushups: 'Max. Liegestütze',
      birthday: 'Geburtstag',
      language: 'Sprache',
      darkMode: 'Dark Mode',
      darkModeDesc: 'Dunkles Farbschema verwenden',
      appearance: 'Darstellung',
      group: 'Gruppe',
      currentGroup: 'Aktuelle Gruppe',
      noGroup: 'Keine Gruppe',
      yourGroupCode: 'Dein Gruppencode',
      joinGroup: 'Beitreten',
      joinOrCreateGroup: 'Gruppe beitreten oder erstellen',
      leaveGroup: 'Gruppe verlassen',
      groupCodePlaceholder: 'GRUPPENCODE',
      enterCode: 'Gruppencode eingeben',
      join: 'Beitreten',
      notifications: 'Benachrichtigungen',
      dailyReminder: 'Tägliche Erinnerung',
      changeTime: 'Zeit ändern',
      testNotification: 'Test-Benachrichtigung senden',
      reminderTime: 'Erinnerungszeit',
      account: 'Konto',
      logout: 'Abmelden',
      deleteAccount: 'Konto löschen',
      legal: 'Rechtliches',
      privacy: 'Datenschutzerklärung',
      terms: 'Nutzungsbedingungen',
      profileUpdated: 'Profil aktualisiert!',
      saveError: 'Fehler beim Speichern',
      joinedGroup: 'Erfolgreich der Gruppe beigetreten!',
      joinGroupError: 'Fehler beim Beitreten der Gruppe',
    },"""

new_german_block = """    settings: {
      title: 'Einstellungen',
      subtitle: 'Passe dein Profil an',
      profile: 'Profil',
      editProfile: 'Profil bearbeiten',
      saveChanges: 'Änderungen speichern',
      nickname: 'Spitzname',
      gender: 'Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      diverse: 'Divers',
      height: 'Größe (cm)',
      weight: 'Gewicht (kg)',
      bodyFat: 'KFA (%) - Optional',
      maxPushups: 'Max. Liegestütze',
      birthday: 'Geburtstag',
      language: 'Sprache',
      darkMode: 'Dark Mode',
      darkModeDesc: 'Dunkles Farbschema verwenden',
      appearance: 'Darstellung',
      installSection: 'App-Installation',
      installDescription: 'Installiere die App, damit sie wie eine native Anwendung funktioniert und offline verfügbar ist.',
      installButton: 'Installationsdialog öffnen',
      installHelp: 'Installationshinweise anzeigen',
      showInstructions: 'Anleitung anzeigen',
      hideInstructions: 'Anleitung verbergen',
      installInstructions: 'Falls kein Dialog erscheint: Öffne die Browser-Menüleiste und wähle \"Zum Startbildschirm hinzufügen\".',
      installInstructionsIos: 'Öffne die Seite in Safari, tippe auf das Teilen-Symbol und wähle \"Zum Home-Bildschirm\".',
      installAlready: 'Die App ist bereits installiert. Du kannst sie direkt vom Home-Bildschirm starten.',
      group: 'Gruppe',
      currentGroup: 'Aktuelle Gruppe',
      noGroup: 'Keine Gruppe',
      yourGroupCode: 'Dein Gruppencode',
      joinGroup: 'Beitreten',
      joinOrCreateGroup: 'Gruppe beitreten oder erstellen',
      leaveGroup: 'Gruppe verlassen',
      groupCodePlaceholder: 'GRUPPENCODE',
      enterCode: 'Gruppencode eingeben',
      join: 'Beitreten',
      notifications: 'Benachrichtigungen',
      dailyReminder: 'Tägliche Erinnerung',
      reminderTime: 'Erinnerungszeit',
      hydrationReminder: 'Hydration (morgens)',
      proteinReminder: 'Protein (mittags)',
      pushupReminder: 'Liegestütze (abends)',
      changeTime: 'Zeit ändern',
      testNotification: 'Test-Benachrichtigung senden',
      account: 'Konto',
      logout: 'Abmelden',
      deleteAccount: 'Konto löschen',
      legal: 'Rechtliches',
      privacy: 'Datenschutzerklärung',
      terms: 'Nutzungsbedingungen',
      profileUpdated: 'Profil aktualisiert!',
      saveError: 'Fehler beim Speichern',
      joinedGroup: 'Erfolgreich der Gruppe beigetreten!',
      joinGroupError: 'Fehler beim Beitreten der Gruppe',
    },"""

if german_block in text:
    TRANSLATIONS_PATH.write_text(text.replace(german_block, new_german_block), encoding="utf-8")
else:
    raise ValueError("Original German settings block not found in translations.ts")
