name: Deploy Production

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_APP_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linting (optional)
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run type checking (optional)
        run: npm run typecheck --if-present
        continue-on-error: true

      - name: Build application
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}

      - name: Copy CNAME for production
        run: |
          if [ -f "ops/pages/CNAME.prod" ]; then
            cp ops/pages/CNAME.prod dist/CNAME
          fi

      - name: Deploy to production pages repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: NewRealm-Projects/winter-arc-app-prod
          branch: gh-pages
          folder: dist
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          clean: true
          commit-message: "Deploy production build from ${{ github.sha }}"
