name: Lighthouse CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    # Only run if CI succeeded (for workflow_run trigger)
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          npm run preview -- --port 4173 &
          sleep 5
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

  mobile-tests:
    runs-on: ubuntu-latest
    # Only run if CI succeeded (for workflow_run trigger)
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Build app
        run: npm run build

      - name: Run mobile device tests
        run: |
          npm run preview -- --port 4174 &
          PREVIEW_PID=$!
          trap "kill $PREVIEW_PID 2>/dev/null" EXIT
          sleep 5

          if [ ! -d tests/mobile ]; then
            echo "No mobile Playwright test directory found, skipping."
            exit 0
          fi

          MOBILE_TEST_COUNT=$(find tests/mobile -type f \( -name "*.spec.ts" -o -name "*.spec.tsx" -o -name "*.spec.js" -o -name "*.spec.jsx" -o -name "*.test.ts" -o -name "*.test.tsx" -o -name "*.test.js" -o -name "*.test.jsx" \) | wc -l)

          if [ "$MOBILE_TEST_COUNT" -eq 0 ]; then
            echo "No mobile Playwright spec files found, skipping."
            exit 0
          fi

          npx playwright test --config=playwright.config.mobile.ts
        env:
          BASE_URL: http://localhost:4174
      - name: Upload mobile test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mobile-screenshots
          path: test-results/
          retention-days: 30
