name: Security Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run weekly security scan every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pull-requests: write

jobs:
  secrets-scan:
    name: Scan for Exposed Secrets
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for comprehensive scan

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run Secret Scan (Tracked Files)
        id: scan-tracked
        run: |
          echo "::group::Scanning git tracked files"
          node scripts/check-secrets.mjs
          echo "::endgroup::"

      - name: Run Secret Scan (Git History)
        id: scan-history
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          echo "::group::Scanning git history"
          node scripts/check-secrets.mjs --history
          echo "::endgroup::"

      - name: Comment on PR (if secrets found)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔒 Security Alert: Potential Secrets Detected

            The automated security scan detected potential secrets in this pull request.

            **Action Required:**
            1. Review the security check logs above
            2. Remove any exposed secrets from your code
            3. Use environment variables instead (see \`.env.example\`)
            4. Rotate any credentials that may have been exposed

            **Need Help?**
            - See [Security Incident Response Guide](../docs/SECURITY_INCIDENT_RESPONSE.md)
            - Run locally: \`npm run lint:secrets\`

            This check must pass before the PR can be merged.
            `
            })

  dependency-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Check for known vulnerabilities
        run: npm audit --production --audit-level=high

  code-security:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
